// src/queries.js:
import { gql } from "@apollo/client";

// Define the GraphQL query to retrieve all authors
export const ALL_AUTHORS = gql`
  query {
    allAuthors {
      # Return values: delivered as a result object.
      name
      born
      bookCount
      id
    }
  }
`;

// GraphQL query to retrieve my (logged in user's) information, inc. favourite genres. Used to set favourite/recommended books.
export const ME = gql`
  query {
    me {
      username
      favouriteGenre
    }
  }
`;

// GraphQL query to retrieve all books.
export const ALL_BOOKS = gql`
  query allBooks($genre: String) {
    # Now get all books filtered by a genre argument.
    allBooks(genre: $genre) {
      title
      published
      author {
        name # author now referes to a object. So, we need to specify specific subfields.
        born
      }
      genres # Added to render genres for all books.
      id
    }
  }
`;

//  GraphQL mutation to log in a user.
export const LOGIN = gql`
  mutation login($username: String!, $password: String!) {
    login(username: $username, password: $password) {
      value
    }
  }
`;

// GraphQL mutation to add a new book.
export const CREATE_BOOK = gql`
  mutation createBook(
    # Define the types and requirements of the data we intend to send from our React frontend to the server.
    $title: String! # The variable title will be a string (required).
    $author: String!
    $published: Int!
    $genres: [String!]! # The variable genres will be an array of strings. Both array and strings are required.
  ) {
    addBook( # addBook: name of the function on your server.
      # Execution: map our variables to the arguments of the backend logic.
      title: $title
      author: $author
      published: $published
      genres: $genres
    ) {
      # Return values: delivered as a result object.
      title
      author {
        name # Now that author is an object, specify author.name subfield.
      }
      published
      genres
      id # Id: generated by the server.
    }
  }
`;

// GraphQL mutation to edit author details by updating born date.
export const EDIT_AUTHOR = gql`
  mutation editAuthor(
    # Define the types and requirements of the data we intend to send from our React frontend to the server.
    $name: String!
    $setBornTo: Int!
  ) {
    editAuthor(
      #  Execution: map our variables to the arguments of the backend logic.
      name: $name # name value taken from dropdown selector. Name must be an existing author. Dropdown removes potential for erronius input.
      setBornTo: $setBornTo
    ) {
      # Return values: delivered as a result object.
      name
      born
      id
    }
  }
`;
