// src/queries.js:
import { gql } from "@apollo/client";

// Define the GraphQL query to retrieve all authors
export const ALL_AUTHORS = gql`
  query {
    allAuthors {
      # Return values: delivered as a result object.
      name
      born
      bookCount
      id
    }
  }
`;

// GraphQL query to retrieve all books.
export const ALL_BOOKS = gql`
  query {
    allBooks {
      title
      published
      author # Remember, author is a string, not an author object with a name attribute.
      id
    }
  }
`;

// GraphQL mutation to add a new book.
export const CREATE_BOOK = gql`
  mutation createBook(
    # Define the types and requirements of the data we intend to send from our React frontend to the server.
    $title: String! # The variable title will be a string (required).
    $author: String!
    $published: Int!
    $genres: [String!]! # The variable genres will be an array of strings. Both array and strings are required.
  ) {
    addBook( # addBook: name of the function on your server.
      # Execution: map our variables to the arguments of the backend logic.
      title: $title
      author: $author
      published: $published
      genres: $genres
    ) {
      # Return values: delivered as a result object.
      title
      author
      published
      genres
      id # Id: generated by the server.
    }
  }
`;

// GraphQL mutation to edit author details by updating born date.
export const EDIT_AUTHOR = gql`
  mutation editAuthor(
    # Define the types and requirements of the data we intend to send from our React frontend to the server.
    $name: String!
    $setBornTo: Int!
  ) {
    editAuthor(
      #  Execution: map our variables to the arguments of the backend logic.
      name: $name # name value taken from dropdown selector. Name must be an existing author. Dropdown removes potential for erronius input.
      setBornTo: $setBornTo
    ) {
      # Return values: delivered as a result object.
      name
      born
      id
    }
  }
`;
